// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MqttConnect(arg1:string):Promise<boolean>;

export function MqttPublish(arg1:string,arg2:string):Promise<boolean>;

export function MqttSubscription(arg1:string):Promise<boolean>;
