// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function MqttConnect(arg1) {
  return window['go']['main']['App']['MqttConnect'](arg1);
}

export function MqttPublish(arg1, arg2) {
  return window['go']['main']['App']['MqttPublish'](arg1, arg2);
}

export function MqttSubscription(arg1) {
  return window['go']['main']['App']['MqttSubscription'](arg1);
}
